// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsympreltgeoellhzvus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeW1wcmVsdGdlb2VsbGh6dnVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzAzOTksImV4cCI6MjA2NTgwNjM5OX0.k-eoqqv9MC7TbztMttuUaAMImgsr1h1npr7OKtLB85k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);